defmodule Ridez.Repo.Migrations.AddRideResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:rides, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:seats, {:array, :map}, null: false)
      add(:required_license, :text)
    end
  end

  def down do
    drop(table(:rides))
  end
end
