defmodule Ridez.Repo.Migrations.AddPeopleAndPersonrideTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rides) do
      remove(:seats)
      add(:seats, :map)
    end

    create table(:person_rides, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:seat, :text, null: false)

      add(
        :ride_id,
        references(:rides,
          column: :id,
          name: "person_rides_ride_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:person_id, :uuid, null: false)
    end

    create table(:people, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:person_rides) do
      modify(
        :person_id,
        references(:people,
          column: :id,
          name: "person_rides_person_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:people) do
      add(:licences, {:array, :text})
    end
  end

  def down do
    alter table(:people) do
      remove(:licences)
    end

    drop(constraint(:person_rides, "person_rides_person_id_fkey"))

    alter table(:person_rides) do
      modify(:person_id, :uuid)
    end

    drop(table(:people))

    drop(constraint(:person_rides, "person_rides_ride_id_fkey"))

    drop(table(:person_rides))

    alter table(:rides) do
      modify(:seats, {:array, :map})
    end
  end
end
