defmodule Ridez.Repo.Migrations.UniquePersonPerRide do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:person_rides, [:person_id, :ride_id],
             name: "person_rides_unique_person_per_ride_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:person_rides, [:person_id, :ride_id],
        name: "person_rides_unique_person_per_ride_index"
      )
    )
  end
end
