defmodule Ridez.Repo.Migrations.InstallLicenseValidationV120250622132921 do
  @moduledoc """
  Installs any extensions that are mentioned in the repo's `installed_extensions/0` callback

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    -- License validation trigger for PersonRide driver seat enforcement
    -- This trigger ensures that only people with the required license can take the driver seat

    CREATE OR REPLACE FUNCTION validate_driver_license_trigger()
    RETURNS TRIGGER AS $$
    DECLARE
    required_license TEXT;
    person_licenses TEXT[];
    BEGIN
    -- Only validate driver seats
    IF NEW.seat != 'driver' THEN
    RETURN NEW;
    END IF;

    -- Get required license and person licenses
    SELECT r.required_license, p.licences
    INTO required_license, person_licenses
    FROM rides r, people p
    WHERE r.id = NEW.ride_id AND p.id = NEW.person_id;

    -- Handle case where person or ride not found
    IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid person_id or ride_id';
    END IF;

    -- No license required - allow
    IF required_license IS NULL THEN
    RETURN NEW;
    END IF;

    -- Check if person has required license
    IF person_licenses IS NULL OR NOT (required_license = ANY(person_licenses)) THEN
    RAISE EXCEPTION 'Driver seat requires % license, person has: %',
                    required_license,
                    COALESCE(array_to_string(person_licenses, ', '), 'no licenses');
    END IF;

    RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    """)

    # Create the trigger on person_rides table
    execute("""
    CREATE TRIGGER validate_driver_license_trigger
      BEFORE INSERT OR UPDATE ON person_rides
      FOR EACH ROW
      EXECUTE FUNCTION validate_driver_license_trigger();
    """)

    # Add comments for people exploring the db
    execute("""
    COMMENT ON FUNCTION validate_driver_license_trigger() IS
    'Validates that only people with the required license can take the driver seat in a ride';
    """)
  end

  def down do
    # Uncomment this if you actually want to uninstall the extensions
    # when this migration is rolled back:

    execute("""
    DROP TRIGGER IF EXISTS validate_driver_license_trigger ON person_rides;
    """)

    execute("""
    DROP FUNCTION IF EXISTS validate_driver_license_trigger();
    """)
  end
end
